name: islami_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter_native_splash: ^2.3.2
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash/
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/
flutter_native_splash:
  android: true
  ios: true
  background_image: "assets/images/splash/splash-light.png"
  background_image_dark: "assets/images/splash/splash-dark.png"
